name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - master
env:
  USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "adopt"

      # Build and run unit tests with Maven
      - name: Build and run tests with Maven
        run: ./mvnw clean verify

      # Login to DockerHub
      - name: Login to DockerHub
        run: docker login -u $USERNAME --password $DOCKER_TOKEN

      #  Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t salmaghabri/with-ga:latest .
          docker push salmaghabri/with-ga:latest
